name: Deploy to GitHub Pages

on:
  # Trigger the workflow every time you push to the `main` branch
  # Using a different branch name? Replace `main` with your branch’s name
  # push:
  #   branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  repository_dispatch:
    types: [my-event]
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  contents: read
  pages: write
  id-token: write
# https://stackoverflow.com/questions/58467939/is-there-a-way-to-get-the-project-folder-name-only-on-a-github-action
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: read-yaml-file
        uses: pietrobolcato/action-read-yaml@1.0.0
        id: read_action_js
        with:
          config: ${{ github.workspace }}/config.yaml
          
      - name: Checkout your vault repository using git
        if: ${{ steps.read_action_js.outputs['vault_repository'] }} != null
        uses: actions/checkout@v4
        with:
          repository: ${{ steps.read_action_js.outputs['vault_repository'] }}
          path: ${{ steps.read_action_js.outputs['vault_directory'] }}
      
      - name: Install Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Install packages
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpx playwright install --with-deps chromium

      - name: Build
        run: pnpm run build
        env:
          CONFIG_SITE_NAME: "\
            https://\
            ${{ github.repository_owner }}\
            .github.io\
            "
          CONFIG_BASE_NAME: /${{ github.event.repository.name }}
          CONFIG_TITLE_NAME: ${{ steps.read_action_js.outputs['title'] }}
          CONFIG_VAULT_NAME: ${{ steps.read_action_js.outputs['vault_directory'] }}
          CONFIG_NOTE_NAME: ${{ steps.read_action_js.outputs['note'] }}
          
      - name: correct wikilink
        run: find . -name "*.html" -print | xargs sed -i s@href=\"/${{ steps.read_action_js.outputs['note'] }}@href=\"/${{ github.event.repository.name }}/${{ steps.read_action_js.outputs['note'] }}@
        
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
